/** 
 * Nombre del Archivo: PanelCurso.java
 * Autores: JULIAN GARCIA RICO (1225435) 
 *          DIEGO FERNANDO BEDOYA (1327749) 
 *          CRISTIAN ALEXANDER VALENCIA TORRES (1329454) 
 *          OSCAR STEVEN ROMERO BERON (1326750) 
 */
package Vista.Administrador;

import Logica.*;
import Patrones.Item;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * Esta clase es cliente de Curso (Patron de diseño Composite) 
 */
public class PanelCurso extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelCurso() {
        initComponents();

        
        // Eventos 
        EventosPanelLogin events = new EventosPanelLogin();
        asignarEventos(events);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Practica = new javax.swing.JTabbedPane();
        panelCurso = new javax.swing.JPanel();
        panelSuperiorCurso = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelNombreCorto = new javax.swing.JLabel();
        inputCodigo = new javax.swing.JTextField();
        inputDescripcion = new javax.swing.JTextField();
        labelDescripcion = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        labelContenido = new javax.swing.JLabel();
        botonCurso = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputContenido = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        panelInferiorCurso = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFases = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panelFase = new javax.swing.JPanel();
        panelSuperiorFase = new javax.swing.JPanel();
        labelCodCurso = new javax.swing.JLabel();
        labelCodFase = new javax.swing.JLabel();
        labelNumHoras = new javax.swing.JLabel();
        labelNumSemanas = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        inputCodigoCurso = new javax.swing.JTextField();
        inputNumSemanas = new javax.swing.JTextField();
        inputCodigoFase = new javax.swing.JTextField();
        inputNumHoras = new javax.swing.JTextField();
        labelContenidoFase = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputContenidoFase = new javax.swing.JTextArea();
        botonFase = new javax.swing.JButton();
        inputTipo = new javax.swing.JComboBox();
        panelInferiorFase = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelPractica = new javax.swing.JPanel();
        panelSuperiorPractica = new javax.swing.JPanel();
        labelCodFasePrac = new javax.swing.JLabel();
        labelCodPrac = new javax.swing.JLabel();
        labelNomPrac = new javax.swing.JLabel();
        inputCodPractica = new javax.swing.JTextField();
        inputNombPrac = new javax.swing.JTextField();
        labelDescPrac = new javax.swing.JLabel();
        botonPractica = new javax.swing.JButton();
        inputFasePrac = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        inputDescPrac = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(750, 505));

        Practica.setBackground(new java.awt.Color(245, 245, 245));

        panelCurso.setBackground(new java.awt.Color(245, 245, 245));
        panelCurso.setPreferredSize(new java.awt.Dimension(750, 505));

        panelSuperiorCurso.setBackground(new java.awt.Color(245, 245, 245));
        panelSuperiorCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNombre.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelNombre.setText("Nombre");

        labelNombreCorto.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelNombreCorto.setText("Nombre corto");

        inputDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDescripcionActionPerformed(evt);
            }
        });

        labelDescripcion.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelDescripcion.setText("Descripción");

        labelCodigo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCodigo.setText("Código");

        labelContenido.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelContenido.setText("Contenido");

        botonCurso.setText("Guardar Curso");

        inputContenido.setColumns(20);
        inputContenido.setRows(5);
        jScrollPane2.setViewportView(inputContenido);

        javax.swing.GroupLayout panelSuperiorCursoLayout = new javax.swing.GroupLayout(panelSuperiorCurso);
        panelSuperiorCurso.setLayout(panelSuperiorCursoLayout);
        panelSuperiorCursoLayout.setHorizontalGroup(
            panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorCursoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre)
                    .addComponent(labelNombreCorto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(inputDescripcion)
                    .addComponent(inputCodigo)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorCursoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCurso)
                .addContainerGap())
        );
        panelSuperiorCursoLayout.setVerticalGroup(
            panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                        .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCodigo)
                            .addComponent(labelContenido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescripcion)
                            .addComponent(inputDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombreCorto)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonCurso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInferiorCurso.setBackground(new java.awt.Color(245, 245, 245));
        panelInferiorCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableFases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableFases);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("LISTA DE FASES");

        javax.swing.GroupLayout panelInferiorCursoLayout = new javax.swing.GroupLayout(panelInferiorCurso);
        panelInferiorCurso.setLayout(panelInferiorCursoLayout);
        panelInferiorCursoLayout.setHorizontalGroup(
            panelInferiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorCursoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelInferiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInferiorCursoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        panelInferiorCursoLayout.setVerticalGroup(
            panelInferiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout panelCursoLayout = new javax.swing.GroupLayout(panelCurso);
        panelCurso.setLayout(panelCursoLayout);
        panelCursoLayout.setHorizontalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInferiorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCursoLayout.setVerticalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoLayout.createSequentialGroup()
                .addComponent(panelSuperiorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInferiorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Practica.addTab("CURSO", panelCurso);

        panelFase.setBackground(new java.awt.Color(245, 245, 245));

        panelSuperiorFase.setBackground(new java.awt.Color(245, 245, 245));
        panelSuperiorFase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCodCurso.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCodCurso.setText("Código Curso");

        labelCodFase.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCodFase.setText("Código Fase");

        labelNumHoras.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelNumHoras.setText("Numero Horas");

        labelNumSemanas.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelNumSemanas.setText("Numero de Semanas");

        labelTipo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelTipo.setText("Tipo");

        inputCodigoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCodigoCursoActionPerformed(evt);
            }
        });

        labelContenidoFase.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelContenidoFase.setText("Contenido");

        inputContenidoFase.setColumns(20);
        inputContenidoFase.setRows(5);
        jScrollPane3.setViewportView(inputContenidoFase);

        botonFase.setText("Guardar Fase");
        botonFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFaseActionPerformed(evt);
            }
        });

        inputTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Presencial", "Virtual" }));

        javax.swing.GroupLayout panelSuperiorFaseLayout = new javax.swing.GroupLayout(panelSuperiorFase);
        panelSuperiorFase.setLayout(panelSuperiorFaseLayout);
        panelSuperiorFaseLayout.setHorizontalGroup(
            panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonFase)
                    .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodFase)
                            .addComponent(labelCodCurso)
                            .addComponent(labelNumHoras)
                            .addComponent(labelNumSemanas)
                            .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inputCodigoCurso)
                                .addComponent(inputNumSemanas)
                                .addComponent(inputTipo, 0, 157, Short.MAX_VALUE))
                            .addComponent(inputCodigoFase, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelContenidoFase, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelSuperiorFaseLayout.setVerticalGroup(
            panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelContenidoFase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelCodCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputCodigoFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCodFase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumHoras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNumSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumSemanas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTipo)
                            .addComponent(inputTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonFase)
                .addContainerGap())
        );

        panelInferiorFase.setBackground(new java.awt.Color(245, 245, 245));
        panelInferiorFase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("LISTA DE PRACTICAS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout panelInferiorFaseLayout = new javax.swing.GroupLayout(panelInferiorFase);
        panelInferiorFase.setLayout(panelInferiorFaseLayout);
        panelInferiorFaseLayout.setHorizontalGroup(
            panelInferiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorFaseLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelInferiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInferiorFaseLayout.setVerticalGroup(
            panelInferiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorFaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFaseLayout = new javax.swing.GroupLayout(panelFase);
        panelFase.setLayout(panelFaseLayout);
        panelFaseLayout.setHorizontalGroup(
            panelFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorFase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInferiorFase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFaseLayout.setVerticalGroup(
            panelFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFaseLayout.createSequentialGroup()
                .addComponent(panelSuperiorFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferiorFase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Practica.addTab("FASE", panelFase);

        panelPractica.setBackground(new java.awt.Color(245, 245, 245));

        panelSuperiorPractica.setBackground(new java.awt.Color(245, 245, 245));
        panelSuperiorPractica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCodFasePrac.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCodFasePrac.setText("Código Fase");

        labelCodPrac.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCodPrac.setText("Código Práctica");

        labelNomPrac.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelNomPrac.setText("Nombre");

        inputCodPractica.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        inputCodPractica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCodPracticaActionPerformed(evt);
            }
        });

        inputNombPrac.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        labelDescPrac.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelDescPrac.setText("Descripción");

        botonPractica.setText("Guardar Practica");

        inputFasePrac.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        inputDescPrac.setColumns(20);
        inputDescPrac.setRows(5);
        jScrollPane6.setViewportView(inputDescPrac);

        javax.swing.GroupLayout panelSuperiorPracticaLayout = new javax.swing.GroupLayout(panelSuperiorPractica);
        panelSuperiorPractica.setLayout(panelSuperiorPracticaLayout);
        panelSuperiorPracticaLayout.setHorizontalGroup(
            panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorPracticaLayout.createSequentialGroup()
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonPractica))
                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodFasePrac, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCodPrac)
                                    .addComponent(labelNomPrac)
                                    .addComponent(labelDescPrac))
                                .addGap(0, 6, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputFasePrac)
                            .addComponent(inputNombPrac, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputCodPractica, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))))
                .addGap(271, 271, 271))
        );
        panelSuperiorPracticaLayout.setVerticalGroup(
            panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodFasePrac)
                    .addComponent(inputFasePrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodPrac)
                    .addComponent(inputCodPractica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNombPrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomPrac))
                .addGap(33, 33, 33)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                        .addComponent(labelDescPrac)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(botonPractica)
                        .addGap(89, 89, 89))))
        );

        javax.swing.GroupLayout panelPracticaLayout = new javax.swing.GroupLayout(panelPractica);
        panelPractica.setLayout(panelPracticaLayout);
        panelPracticaLayout.setHorizontalGroup(
            panelPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorPractica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPracticaLayout.setVerticalGroup(
            panelPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorPractica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Practica.addTab("PRÁCTICA", panelPractica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Practica, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Practica)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDescripcionActionPerformed

    private void inputCodigoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCodigoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodigoCursoActionPerformed

    private void botonFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFaseActionPerformed

    private void inputCodPracticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCodPracticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodPracticaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Practica;
    private javax.swing.JButton botonCurso;
    private javax.swing.JButton botonFase;
    private javax.swing.JButton botonPractica;
    private javax.swing.JTextField inputCodPractica;
    private javax.swing.JTextField inputCodigo;
    private javax.swing.JTextField inputCodigoCurso;
    private javax.swing.JTextField inputCodigoFase;
    private javax.swing.JTextArea inputContenido;
    private javax.swing.JTextArea inputContenidoFase;
    private javax.swing.JTextArea inputDescPrac;
    private javax.swing.JTextField inputDescripcion;
    private javax.swing.JTextField inputFasePrac;
    private javax.swing.JTextField inputNombPrac;
    private javax.swing.JTextField inputNumHoras;
    private javax.swing.JTextField inputNumSemanas;
    private javax.swing.JComboBox inputTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelCodCurso;
    private javax.swing.JLabel labelCodFase;
    private javax.swing.JLabel labelCodFasePrac;
    private javax.swing.JLabel labelCodPrac;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelContenido;
    private javax.swing.JLabel labelContenidoFase;
    private javax.swing.JLabel labelDescPrac;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelNomPrac;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreCorto;
    private javax.swing.JLabel labelNumHoras;
    private javax.swing.JLabel labelNumSemanas;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelCurso;
    private javax.swing.JPanel panelFase;
    private javax.swing.JPanel panelInferiorCurso;
    private javax.swing.JPanel panelInferiorFase;
    private javax.swing.JPanel panelPractica;
    private javax.swing.JPanel panelSuperiorCurso;
    private javax.swing.JPanel panelSuperiorFase;
    private javax.swing.JPanel panelSuperiorPractica;
    private javax.swing.JTable tableFases;
    // End of variables declaration//GEN-END:variables

                
    private void asignarEventos(EventosPanelLogin events){
        botonCurso.addActionListener(events);
        botonFase.addActionListener(events);
        botonPractica.addActionListener(events);
    } // Fin del metodo asignarEventos
    
   
    
   
    
    
    
    
    private void limpiarPanelFase(){
        
        //SOLO PARA TERCERA ENTRAGA DE PATRONES DE DISEÑO - MODIFICAR
        inputCodigoCurso.setText("");
        inputCodigoFase.setText("");
        inputNumHoras.setText("");
        inputNumSemanas.setText("");
        // inputTipo.getSelectedItem
        inputContenidoFase.setText("");                
    } // Fin del metodo limpiarPanelFase
    
    private void limpiarPanelPractica(){
        //SOLO PARA TERCERA ENTRAGA DE PATRONES DE DISEÑO - MODIFICAR
        inputFasePrac.setText("");
        inputCodPractica.setText("");
        inputNombPrac.setText("");
        inputDescPrac.setText("");        
    } // Fin del metodo limpiarPanelPractica
    
    private class EventosPanelLogin implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == botonCurso) {
               
                
            }
            if (e.getSource() == botonFase){
                
            }
            if (e.getSource() == botonPractica){
              
            }
        }   
    } // Fin de la clase EventosPanelLogin

} // Fin de la clase PanelLogin
