/** 
 * Nombre del Archivo: PanelCurso.java
 * Autores: JULIAN GARCIA RICO (1225435) 
 *          DIEGO FERNANDO BEDOYA (1327749) 
 *          CRISTIAN ALEXANDER VALENCIA TORRES (1329454) 
 *          OSCAR STEVEN ROMERO BERON (1326750) 
 */
package Vista.Administrador;

import Controlador.ControladorAdministrador;
import Excepciones.ExcepcionDatos;
import Logica.*;
import Patrones.Item;
import Patrones.Observador;
import Patrones.Sujeto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 * Esta clase es cliente de Curso (Patron de diseño Composite) 
 */
public class PanelCursoUpdate extends javax.swing.JPanel implements Observador {
       private ArrayList <String> idNombreCurso;
       private ControladorAdministrador controladorAdministrador;

    /**
     * Creates new form PanelLogin
     */
    public PanelCursoUpdate(ControladorAdministrador controladorAdministrador) {
        initComponents();
        this.controladorAdministrador = controladorAdministrador;
        this.idNombreCurso = controladorAdministrador.getIdNombreCurso();
        //Observador lista de cursos
        
        
        
        // Eventos 
        EventosPanelLogin events = new EventosPanelLogin();
        asignarEventos(events);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Practica = new javax.swing.JTabbedPane();
        panelCurso = new javax.swing.JPanel();
        panelSuperiorCurso = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelNombreCorto = new javax.swing.JLabel();
        inputDescripcion = new javax.swing.JTextField();
        labelDescripcion = new javax.swing.JLabel();
        labelContenido = new javax.swing.JLabel();
        botonCurso = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputContenido = new javax.swing.JTextArea();
        inputNombre = new javax.swing.JTextField();
        inputNombreCorto = new javax.swing.JTextField();
        botonLimpiarCurso = new javax.swing.JButton();
        panelInferiorCurso = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        InputBusquedaNombreCurso = new javax.swing.JTextField();
        botonBuscarCurso = new javax.swing.JButton();
        campoBusquedaCurso = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelFase = new javax.swing.JPanel();
        panelSuperiorFase = new javax.swing.JPanel();
        labelNumHoras = new javax.swing.JLabel();
        labelNumSemanas = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        inputNumSemanas = new javax.swing.JTextField();
        inputNumHoras = new javax.swing.JTextField();
        labelContenidoFase = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputContenidoFase = new javax.swing.JTextArea();
        botonFase = new javax.swing.JButton();
        inputTipo = new javax.swing.JComboBox();
        botonLimpiarFase = new javax.swing.JButton();
        panelInferiorFase = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboCurso = new javax.swing.JComboBox();
        comboListFasesPF = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        panelPractica = new javax.swing.JPanel();
        panelSuperiorPractica = new javax.swing.JPanel();
        labelCodFasePrac = new javax.swing.JLabel();
        labelNomPrac = new javax.swing.JLabel();
        inputNombPrac = new javax.swing.JTextField();
        labelDescPrac = new javax.swing.JLabel();
        botonPractica = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        inputDescPrac = new javax.swing.JTextArea();
        comboFases = new javax.swing.JComboBox();
        botonListarFases = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        inputPorcentaje = new javax.swing.JTextField();
        botonLimpiarPractica = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(750, 505));

        Practica.setBackground(new java.awt.Color(245, 245, 245));

        panelCurso.setBackground(new java.awt.Color(245, 245, 245));
        panelCurso.setPreferredSize(new java.awt.Dimension(750, 505));

        panelSuperiorCurso.setBackground(new java.awt.Color(245, 245, 245));
        panelSuperiorCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNombre.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelNombre.setText("Nombre");

        labelNombreCorto.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelNombreCorto.setText("Nombre corto");

        inputDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDescripcionActionPerformed(evt);
            }
        });

        labelDescripcion.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelDescripcion.setText("Descripción");

        labelContenido.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelContenido.setText("Contenido");

        botonCurso.setText("Guardar Curso");

        inputContenido.setColumns(20);
        inputContenido.setRows(5);
        jScrollPane2.setViewportView(inputContenido);

        botonLimpiarCurso.setText("Limpiar");

        javax.swing.GroupLayout panelSuperiorCursoLayout = new javax.swing.GroupLayout(panelSuperiorCurso);
        panelSuperiorCurso.setLayout(panelSuperiorCursoLayout);
        panelSuperiorCursoLayout.setHorizontalGroup(
            panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre)
                            .addComponent(labelNombreCorto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNombreCorto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(botonLimpiarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(botonCurso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSuperiorCursoLayout.setVerticalGroup(
            panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescripcion)
                    .addComponent(inputDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNombreCorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreCorto))
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(labelContenido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiarCurso)
                    .addComponent(botonCurso))
                .addGap(35, 35, 35))
        );

        panelInferiorCurso.setBackground(new java.awt.Color(245, 245, 245));
        panelInferiorCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("BÚSQUEDA DE CURSO");

        botonBuscarCurso.setText("Buscar");

        campoBusquedaCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id_curso", "nombre", "nombre_corto" }));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Campo");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setText("Valor");

        javax.swing.GroupLayout panelInferiorCursoLayout = new javax.swing.GroupLayout(panelInferiorCurso);
        panelInferiorCurso.setLayout(panelInferiorCursoLayout);
        panelInferiorCursoLayout.setHorizontalGroup(
            panelInferiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelInferiorCursoLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputBusquedaNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoBusquedaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonBuscarCurso)
                .addGap(131, 131, 131))
        );
        panelInferiorCursoLayout.setVerticalGroup(
            panelInferiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelInferiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputBusquedaNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarCurso)
                    .addComponent(campoBusquedaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCursoLayout = new javax.swing.GroupLayout(panelCurso);
        panelCurso.setLayout(panelCursoLayout);
        panelCursoLayout.setHorizontalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInferiorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCursoLayout.setVerticalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCursoLayout.createSequentialGroup()
                .addComponent(panelInferiorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSuperiorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Practica.addTab("CURSO", panelCurso);

        panelFase.setBackground(new java.awt.Color(245, 245, 245));
        panelFase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelFaseMouseClicked(evt);
            }
        });

        panelSuperiorFase.setBackground(new java.awt.Color(245, 245, 245));
        panelSuperiorFase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNumHoras.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelNumHoras.setText("Numero Horas");

        labelNumSemanas.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelNumSemanas.setText("Numero de Semanas");

        labelTipo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelTipo.setText("Tipo");

        labelContenidoFase.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelContenidoFase.setText("Contenido");

        inputContenidoFase.setColumns(20);
        inputContenidoFase.setRows(5);
        jScrollPane3.setViewportView(inputContenidoFase);

        botonFase.setText("Guardar Fase");
        botonFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFaseActionPerformed(evt);
            }
        });

        inputTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Presencial", "Virtual" }));

        botonLimpiarFase.setText("Limpiar");

        javax.swing.GroupLayout panelSuperiorFaseLayout = new javax.swing.GroupLayout(panelSuperiorFase);
        panelSuperiorFase.setLayout(panelSuperiorFaseLayout);
        panelSuperiorFaseLayout.setHorizontalGroup(
            panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNumHoras)
                                    .addComponent(labelNumSemanas)
                                    .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(inputNumSemanas)
                                        .addComponent(inputTipo, 0, 157, Short.MAX_VALUE))
                                    .addComponent(inputNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(184, 184, 184))
                            .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                                .addComponent(labelContenidoFase, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonLimpiarFase)
                        .addGap(18, 18, 18)
                        .addComponent(botonFase)
                        .addGap(168, 168, 168))))
        );
        panelSuperiorFaseLayout.setVerticalGroup(
            panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumHoras)
                    .addComponent(inputNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNumSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumSemanas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(inputTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContenidoFase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonFase)
                    .addComponent(botonLimpiarFase))
                .addContainerGap())
        );

        panelInferiorFase.setBackground(new java.awt.Color(245, 245, 245));
        panelInferiorFase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setText("Código Fase");

        jButton1.setText("Buscar");

        comboListFasesPF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setText("Código Curso");

        javax.swing.GroupLayout panelInferiorFaseLayout = new javax.swing.GroupLayout(panelInferiorFase);
        panelInferiorFase.setLayout(panelInferiorFaseLayout);
        panelInferiorFaseLayout.setHorizontalGroup(
            panelInferiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorFaseLayout.createSequentialGroup()
                .addGroup(panelInferiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInferiorFaseLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2))
                    .addGroup(panelInferiorFaseLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboListFasesPF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInferiorFaseLayout.setVerticalGroup(
            panelInferiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorFaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelInferiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1)
                    .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboListFasesPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFaseLayout = new javax.swing.GroupLayout(panelFase);
        panelFase.setLayout(panelFaseLayout);
        panelFaseLayout.setHorizontalGroup(
            panelFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorFase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInferiorFase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFaseLayout.setVerticalGroup(
            panelFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInferiorFase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSuperiorFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Practica.addTab("FASE", panelFase);

        panelPractica.setBackground(new java.awt.Color(245, 245, 245));

        panelSuperiorPractica.setBackground(new java.awt.Color(245, 245, 245));
        panelSuperiorPractica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCodFasePrac.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCodFasePrac.setText("Código Fase");

        labelNomPrac.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelNomPrac.setText("Nombre");

        inputNombPrac.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N

        labelDescPrac.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelDescPrac.setText("Descripción");

        botonPractica.setText("Guardar Practica");

        inputDescPrac.setColumns(20);
        inputDescPrac.setRows(5);
        jScrollPane6.setViewportView(inputDescPrac);

        botonListarFases.setText("LISTAR");

        jLabel3.setText("Porcentaje");

        botonLimpiarPractica.setText("Limpiar");

        javax.swing.GroupLayout panelSuperiorPracticaLayout = new javax.swing.GroupLayout(panelSuperiorPractica);
        panelSuperiorPractica.setLayout(panelSuperiorPracticaLayout);
        panelSuperiorPracticaLayout.setHorizontalGroup(
            panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorPracticaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonLimpiarPractica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonPractica))
                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCodFasePrac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNomPrac)
                                            .addComponent(labelDescPrac))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(60, 60, 60)))
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                                .addComponent(comboFases, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonListarFases))
                            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputPorcentaje, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNombPrac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(265, 265, 265))
        );
        panelSuperiorPracticaLayout.setVerticalGroup(
            panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCodFasePrac)
                    .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonListarFases)
                        .addComponent(comboFases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNombPrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomPrac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonPractica)
                            .addComponent(botonLimpiarPractica)))
                    .addComponent(labelDescPrac))
                .addGap(175, 175, 175))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPracticaLayout = new javax.swing.GroupLayout(panelPractica);
        panelPractica.setLayout(panelPracticaLayout);
        panelPracticaLayout.setHorizontalGroup(
            panelPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorPractica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPracticaLayout.setVerticalGroup(
            panelPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPracticaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSuperiorPractica, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Practica.addTab("PRÁCTICA", panelPractica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Practica)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Practica, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDescripcionActionPerformed

    private void botonFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFaseActionPerformed

    private void panelFaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelFaseMouseClicked
        
    }//GEN-LAST:event_panelFaseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputBusquedaNombreCurso;
    private javax.swing.JTabbedPane Practica;
    private javax.swing.JButton botonBuscarCurso;
    private javax.swing.JButton botonCurso;
    private javax.swing.JButton botonFase;
    private javax.swing.JButton botonLimpiarCurso;
    private javax.swing.JButton botonLimpiarFase;
    private javax.swing.JButton botonLimpiarPractica;
    private javax.swing.JButton botonListarFases;
    private javax.swing.JButton botonPractica;
    private javax.swing.JComboBox campoBusquedaCurso;
    private javax.swing.JComboBox comboCurso;
    private javax.swing.JComboBox comboFases;
    private javax.swing.JComboBox comboListFasesPF;
    private javax.swing.JTextArea inputContenido;
    private javax.swing.JTextArea inputContenidoFase;
    private javax.swing.JTextArea inputDescPrac;
    private javax.swing.JTextField inputDescripcion;
    private javax.swing.JTextField inputNombPrac;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNombreCorto;
    private javax.swing.JTextField inputNumHoras;
    private javax.swing.JTextField inputNumSemanas;
    private javax.swing.JTextField inputPorcentaje;
    private javax.swing.JComboBox inputTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel labelCodFasePrac;
    private javax.swing.JLabel labelContenido;
    private javax.swing.JLabel labelContenidoFase;
    private javax.swing.JLabel labelDescPrac;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelNomPrac;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreCorto;
    private javax.swing.JLabel labelNumHoras;
    private javax.swing.JLabel labelNumSemanas;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelCurso;
    private javax.swing.JPanel panelFase;
    private javax.swing.JPanel panelInferiorCurso;
    private javax.swing.JPanel panelInferiorFase;
    private javax.swing.JPanel panelPractica;
    private javax.swing.JPanel panelSuperiorCurso;
    private javax.swing.JPanel panelSuperiorFase;
    private javax.swing.JPanel panelSuperiorPractica;
    // End of variables declaration//GEN-END:variables

       
    
                
    private void asignarEventos(EventosPanelLogin events){
//        botonCurso.addActionListener(events);
//        botonFase.addActionListener(events);
//        botonPractica.addActionListener(events);
//        
//        botonListarFases.addActionListener(events);
//        botonLimpiarCurso.addActionListener(events);
//        botonLimpiarFase.addActionListener(events);
//        botonLimpiarPractica.addActionListener(events);
        
        botonBuscarCurso.addActionListener(events);
       
    } // Fin del metodo asignarEventos
    
   
    private void limpiarPanelFase(){
        inputNumHoras.setText("");
        inputNumSemanas.setText("");
        inputContenidoFase.setText("");                
    } // Fin del metodo limpiarPanelFase
    
    private void limpiarPanelPractica(){
        
        
        
        inputNombPrac.setText("");
        inputDescPrac.setText("");
        inputPorcentaje.setText("");       
    } // Fin del metodo limpiarPanelPractica
    
    private void limpiarPanelCurso(){
        inputNombre.setText("");
        inputNombreCorto.setText("");
        inputDescripcion.setText("");
        inputContenido.setText("");
    }
    
   
    
   
            
    private void llenarFases(){
       // controladorAdministrador = ControladorAdministrador.getInstance();
//        String result = "";
//        result = controladorAdministrador.listFasesIds();
//        ArrayList <String> idNombresFases = controladorAdministrador.getIdNombreFases();
//        if(idNombresFases!=null){
//            for(int i = 0; i < idNombresFases.size(); i++){
//            comboFases.addItem(idNombresFases.get(i));
//            }
//        }else{
//            JOptionPane.showMessageDialog(null, result);
//        }
        
    }
    
    public void llenarCursos(){
       comboCurso.removeAllItems();
      String result = "";
        if(idNombreCurso!=null){
            for(int i = 0; i < idNombreCurso.size(); i++){
            comboCurso.addItem(idNombreCurso.get(i));
            }
        }else{
            JOptionPane.showMessageDialog(null, result);
        }
     }
    

    @Override
    public void actualizar(Sujeto objSujeto) {
        System.out.print("se actualizaron cursos");
        llenarCursos();
    }
    
   
    
    
    
    private class EventosPanelLogin implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            
           if(e.getSource() == botonBuscarCurso){
                String campo = (String) campoBusquedaCurso.getSelectedItem();
                String valor = InputBusquedaNombreCurso.getText();
                String result = controladorAdministrador.buscarCurso(campo, valor);
                
        
               
           }
        }   
    } // Fin de la clase EventosPanelLogin

} // Fin de la clase PanelLogin
