/** 
 * Nombre del Archivo: Item.java
 * Autores: JULIAN GARCIA RICO (1225435) 
 *          DIEGO FERNANDO BEDOYA (1327749) 
 *          CRISTIAN ALEXANDER VALENCIA TORRES (1329454) 
 *          OSCAR STEVEN ROMERO BERON (1326750) 
 */
package Vista.Leader_Teacher;

import Logica.Matricula;
import Logica.Tarea;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author oscar
 */
public class PanelConsultarCalificacion1 extends javax.swing.JPanel {

    ArrayList <Tarea> listaTareas = new ArrayList <> ();
    Matricula matricula = new Matricula ();
    
    /**
     * Creates new form PanelLogin
     */
    public PanelConsultarCalificacion1() {
        initComponents();

        
        
        // Eventos 
        EventosPanelConsultarCalificacion events = new EventosPanelConsultarCalificacion();
        asignarEventos(events);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        labelConsulCalificacion = new javax.swing.JLabel();
        labelCedulaLt = new javax.swing.JLabel();
        inputCedulaLt = new javax.swing.JTextField();
        botonListarCursos = new javax.swing.JButton();
        scollPaneListaCursos = new javax.swing.JScrollPane();
        listaCursos = new javax.swing.JList();
        botonVerCalificacin = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        panelInferior = new javax.swing.JPanel();
        labelNotaDefinitiva = new javax.swing.JLabel();
        inputNotaDefinitiva = new javax.swing.JTextField();
        scrollPaneTabla = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 245, 245));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(750, 505));

        panelSuperior.setBackground(new java.awt.Color(245, 245, 245));
        panelSuperior.setBorder(null);

        labelConsulCalificacion.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelConsulCalificacion.setForeground(new java.awt.Color(15, 15, 111));
        labelConsulCalificacion.setText("CONSULTAR CALIFICACIONES");

        labelCedulaLt.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCedulaLt.setText("Cedula Leader Teacher:");

        botonListarCursos.setText("Listar Cursos");
        botonListarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarCursosActionPerformed(evt);
            }
        });

        scollPaneListaCursos.setViewportView(listaCursos);

        botonVerCalificacin.setText("Ver calificaciones");
        botonVerCalificacin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerCalificacinActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSuperiorLayout.createSequentialGroup()
                                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCedulaLt)
                                    .addComponent(botonListarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputCedulaLt, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scollPaneListaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelConsulCalificacion))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonVerCalificacin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCancelar)
                        .addGap(55, 55, 55))))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelConsulCalificacion)
                .addGap(18, 18, 18)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCedulaLt)
                    .addComponent(inputCedulaLt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonListarCursos)
                    .addComponent(scollPaneListaCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerCalificacin)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );

        panelInferior.setBackground(new java.awt.Color(245, 245, 245));
        panelInferior.setBorder(null);

        labelNotaDefinitiva.setText("Nota Definitiva ");

        inputNotaDefinitiva.setEditable(false);
        inputNotaDefinitiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNotaDefinitivaActionPerformed(evt);
            }
        });

        scrollPaneTabla.setBackground(new java.awt.Color(245, 245, 245));

        tablaNotas.setBackground(new java.awt.Color(245, 245, 245));
        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Practica", "Porcentaje Pracitca", "Nota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneTabla.setViewportView(tablaNotas);
        if (tablaNotas.getColumnModel().getColumnCount() > 0) {
            tablaNotas.getColumnModel().getColumn(0).setResizable(false);
            tablaNotas.getColumnModel().getColumn(1).setResizable(false);
            tablaNotas.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInferiorLayout.createSequentialGroup()
                        .addComponent(labelNotaDefinitiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNotaDefinitiva, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNotaDefinitiva)
                    .addComponent(inputNotaDefinitiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarCursosActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_botonListarCursosActionPerformed

    private void inputNotaDefinitivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNotaDefinitivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNotaDefinitivaActionPerformed

    private void botonVerCalificacinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerCalificacinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerCalificacinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonListarCursos;
    private javax.swing.JButton botonVerCalificacin;
    private javax.swing.JTextField inputCedulaLt;
    private javax.swing.JTextField inputNotaDefinitiva;
    private javax.swing.JLabel labelCedulaLt;
    private javax.swing.JLabel labelConsulCalificacion;
    private javax.swing.JLabel labelNotaDefinitiva;
    private javax.swing.JList listaCursos;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JScrollPane scollPaneListaCursos;
    private javax.swing.JScrollPane scrollPaneTabla;
    private javax.swing.JTable tablaNotas;
    // End of variables declaration//GEN-END:variables


    private void asignarEventos(EventosPanelConsultarCalificacion events){
        botonListarCursos.addActionListener(events);
    } // Fin del metodo asignarEventos
        
    private void actualizarListaCursos() {
    
    } // Fin del metodo actualizarListaCursos
    
    private class EventosPanelConsultarCalificacion implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == botonListarCursos) {
                
            }
        }
    
    } // Fin de la clase EventosPanelLogin
    
} // Fin de la clase PanelLogin
