/** 
 * Nombre del Archivo: Item.java
 * Autores: JULIAN GARCIA RICO (1225435) 
 *          DIEGO FERNANDO BEDOYA (1327749) 
 *          CRISTIAN ALEXANDER VALENCIA TORRES (1329454) 
 *          OSCAR STEVEN ROMERO BERON (1326750) 
 */
package Vista.Coordinador;

import Controlador.ControladorReportes;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author oscar
 */
public class PanelReporte extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelReporte() {
        initComponents();
                
        // Eventos 
        EventosPanelLogin events = new EventosPanelLogin();
        asignarEventos(events);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscarMesAno = new javax.swing.JPanel();
        labelReportEspecifico = new javax.swing.JLabel();
        labelAno = new javax.swing.JLabel();
        inputAno = new com.toedter.calendar.JYearChooser();
        labelMes = new javax.swing.JLabel();
        inputMes = new com.toedter.calendar.JMonthChooser();
        botonBuscarMesAno = new javax.swing.JButton();
        panelCursoEstDepart = new javax.swing.JPanel();
        labelCodCursoCED = new javax.swing.JLabel();
        labelReporteEspecifico2 = new javax.swing.JLabel();
        labelDepartementoCDE = new javax.swing.JLabel();
        scrollPanelListDepar = new javax.swing.JScrollPane();
        listDepart = new javax.swing.JList();
        botonReporteCDE = new javax.swing.JButton();
        inputCursoCodCDE = new javax.swing.JComboBox();
        panelEstdianteNotas = new javax.swing.JPanel();
        labelReporteEspecifico3 = new javax.swing.JLabel();
        labelCedulaNTL = new javax.swing.JLabel();
        inputCedulaNLT = new javax.swing.JTextField();
        botonReporteNLT = new javax.swing.JButton();
        panelCursoHistorico = new javax.swing.JPanel();
        labelCodCursoHEC = new javax.swing.JLabel();
        labelReporteEspecifico4 = new javax.swing.JLabel();
        botonReporteHEC = new javax.swing.JButton();
        inputCodCurosHEC = new javax.swing.JComboBox();
        panelCursoMenosAvance = new javax.swing.JPanel();
        labelReporteEspecifico5 = new javax.swing.JLabel();
        labelCodCohorteCMA = new javax.swing.JLabel();
        botonReporteCMA = new javax.swing.JButton();
        inputCodCohorteCMA = new javax.swing.JComboBox();
        panelLTMesDepart = new javax.swing.JPanel();
        labelReporteEspecifico6 = new javax.swing.JLabel();
        inputAnoEMD = new com.toedter.calendar.JYearChooser();
        labelAnoEMD = new javax.swing.JLabel();
        labelMesEMD = new javax.swing.JLabel();
        inputMesEMD = new com.toedter.calendar.JMonthChooser();
        botonReporteEMD = new javax.swing.JButton();
        panelSuperior = new javax.swing.JPanel();
        labelReporte = new javax.swing.JLabel();
        labelListaReportes = new javax.swing.JLabel();
        comboReportes = new javax.swing.JComboBox();
        panelInferior = new javax.swing.JPanel();

        panelBuscarMesAno.setBackground(new java.awt.Color(245, 245, 245));
        panelBuscarMesAno.setBorder(null);

        labelReportEspecifico.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelReportEspecifico.setForeground(new java.awt.Color(15, 15, 111));
        labelReportEspecifico.setText("Cursos con mayor asistencia en el mes (Top 10)");

        labelAno.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelAno.setText("Año:");

        labelMes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelMes.setText("Mes:");

        botonBuscarMesAno.setText("Generar Reporte");

        javax.swing.GroupLayout panelBuscarMesAnoLayout = new javax.swing.GroupLayout(panelBuscarMesAno);
        panelBuscarMesAno.setLayout(panelBuscarMesAnoLayout);
        panelBuscarMesAnoLayout.setHorizontalGroup(
            panelBuscarMesAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarMesAnoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelBuscarMesAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarMesAnoLayout.createSequentialGroup()
                        .addComponent(labelMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputAno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonBuscarMesAno)
                    .addComponent(labelReportEspecifico))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        panelBuscarMesAnoLayout.setVerticalGroup(
            panelBuscarMesAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarMesAnoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelReportEspecifico)
                .addGap(30, 30, 30)
                .addGroup(panelBuscarMesAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAno)
                    .addComponent(inputAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMes)
                    .addComponent(inputMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(botonBuscarMesAno)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelCursoEstDepart.setBackground(new java.awt.Color(245, 245, 245));
        panelCursoEstDepart.setBorder(null);

        labelCodCursoCED.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCodCursoCED.setText("Cod del Curso:");

        labelReporteEspecifico2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelReporteEspecifico2.setForeground(new java.awt.Color(15, 15, 111));
        labelReporteEspecifico2.setText("Detalle de estudiantes en un curso por departamentos");

        labelDepartementoCDE.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelDepartementoCDE.setText("Departamento: ");

        listDepart.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Amazonas", "Antioquia", "Arauca", "Atlantico", "Bolivar", "Boyacá ", "Caldas ", "Caquetá ", "Casanare", "Cauca ", "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira", "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindio", "Risaralda", "San Andres y Providencia", "Santander", "Sucre ", "Tolima", "Valle del Cauca", "Vaupés ", "Vichada" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollPanelListDepar.setViewportView(listDepart);

        botonReporteCDE.setText("Generar Reporte");

        inputCursoCodCDE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "...................................." }));

        javax.swing.GroupLayout panelCursoEstDepartLayout = new javax.swing.GroupLayout(panelCursoEstDepart);
        panelCursoEstDepart.setLayout(panelCursoEstDepartLayout);
        panelCursoEstDepartLayout.setHorizontalGroup(
            panelCursoEstDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoEstDepartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelCursoEstDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCursoEstDepartLayout.createSequentialGroup()
                        .addComponent(labelReporteEspecifico2)
                        .addContainerGap(126, Short.MAX_VALUE))
                    .addGroup(panelCursoEstDepartLayout.createSequentialGroup()
                        .addGroup(panelCursoEstDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCursoEstDepartLayout.createSequentialGroup()
                                .addComponent(labelCodCursoCED)
                                .addGap(6, 6, 6)
                                .addComponent(inputCursoCodCDE, 0, 173, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(labelDepartementoCDE))
                            .addGroup(panelCursoEstDepartLayout.createSequentialGroup()
                                .addComponent(botonReporteCDE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPanelListDepar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        panelCursoEstDepartLayout.setVerticalGroup(
            panelCursoEstDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCursoEstDepartLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelReporteEspecifico2)
                .addGap(28, 28, 28)
                .addGroup(panelCursoEstDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanelListDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDepartementoCDE)
                    .addGroup(panelCursoEstDepartLayout.createSequentialGroup()
                        .addGroup(panelCursoEstDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCodCursoCED)
                            .addComponent(inputCursoCodCDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(botonReporteCDE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelEstdianteNotas.setBackground(new java.awt.Color(245, 245, 245));
        panelEstdianteNotas.setBorder(null);

        labelReporteEspecifico3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelReporteEspecifico3.setForeground(new java.awt.Color(15, 15, 111));
        labelReporteEspecifico3.setText("Detalle del reporte de notas por estudiante");

        labelCedulaNTL.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCedulaNTL.setText("Cedula Leader Teacher");

        botonReporteNLT.setBackground(new java.awt.Color(245, 245, 245));
        botonReporteNLT.setText("Generar Reporte");

        javax.swing.GroupLayout panelEstdianteNotasLayout = new javax.swing.GroupLayout(panelEstdianteNotas);
        panelEstdianteNotas.setLayout(panelEstdianteNotasLayout);
        panelEstdianteNotasLayout.setHorizontalGroup(
            panelEstdianteNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstdianteNotasLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelEstdianteNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonReporteNLT)
                    .addGroup(panelEstdianteNotasLayout.createSequentialGroup()
                        .addComponent(labelCedulaNTL)
                        .addGap(18, 18, 18)
                        .addComponent(inputCedulaNLT, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelReporteEspecifico3, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        panelEstdianteNotasLayout.setVerticalGroup(
            panelEstdianteNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstdianteNotasLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelReporteEspecifico3)
                .addGap(30, 30, 30)
                .addGroup(panelEstdianteNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCedulaNTL)
                    .addComponent(inputCedulaNLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(botonReporteNLT)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        panelCursoHistorico.setBackground(new java.awt.Color(245, 245, 245));
        panelCursoHistorico.setBorder(null);

        labelCodCursoHEC.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCodCursoHEC.setText("Codigo del Curso:");

        labelReporteEspecifico4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelReporteEspecifico4.setForeground(new java.awt.Color(15, 15, 111));
        labelReporteEspecifico4.setText("Historico de estudiantes que ha ganada un curso");

        botonReporteHEC.setText("Generar Reporte");

        inputCodCurosHEC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelCursoHistoricoLayout = new javax.swing.GroupLayout(panelCursoHistorico);
        panelCursoHistorico.setLayout(panelCursoHistoricoLayout);
        panelCursoHistoricoLayout.setHorizontalGroup(
            panelCursoHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoHistoricoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelCursoHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCursoHistoricoLayout.createSequentialGroup()
                        .addComponent(labelCodCursoHEC)
                        .addGap(18, 18, 18)
                        .addComponent(inputCodCurosHEC, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelReporteEspecifico4)
                    .addComponent(botonReporteHEC))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        panelCursoHistoricoLayout.setVerticalGroup(
            panelCursoHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCursoHistoricoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelReporteEspecifico4)
                .addGap(30, 30, 30)
                .addGroup(panelCursoHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodCursoHEC)
                    .addComponent(inputCodCurosHEC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(botonReporteHEC)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelCursoMenosAvance.setBackground(new java.awt.Color(245, 245, 245));

        labelReporteEspecifico5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelReporteEspecifico5.setForeground(new java.awt.Color(15, 15, 111));
        labelReporteEspecifico5.setText("Curso con menos potencial de avance (TOP 5)");

        labelCodCohorteCMA.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelCodCohorteCMA.setText("Codigo de la cohorte: ");

        botonReporteCMA.setText("Generar Reporte");
        botonReporteCMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteCMAActionPerformed(evt);
            }
        });

        inputCodCohorteCMA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelCursoMenosAvanceLayout = new javax.swing.GroupLayout(panelCursoMenosAvance);
        panelCursoMenosAvance.setLayout(panelCursoMenosAvanceLayout);
        panelCursoMenosAvanceLayout.setHorizontalGroup(
            panelCursoMenosAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoMenosAvanceLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelCursoMenosAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonReporteCMA)
                    .addGroup(panelCursoMenosAvanceLayout.createSequentialGroup()
                        .addComponent(labelCodCohorteCMA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCodCohorteCMA, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelReporteEspecifico5))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        panelCursoMenosAvanceLayout.setVerticalGroup(
            panelCursoMenosAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoMenosAvanceLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelReporteEspecifico5)
                .addGap(30, 30, 30)
                .addGroup(panelCursoMenosAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodCohorteCMA)
                    .addComponent(inputCodCohorteCMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(botonReporteCMA)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panelLTMesDepart.setBackground(new java.awt.Color(245, 245, 245));

        labelReporteEspecifico6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelReporteEspecifico6.setForeground(new java.awt.Color(15, 15, 111));
        labelReporteEspecifico6.setText("Estudiantes que han llegado en el mes por departamento");

        labelAnoEMD.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelAnoEMD.setText("Año:");

        labelMesEMD.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        labelMesEMD.setText("Mes:");

        botonReporteEMD.setText("Generar Reporte");
        botonReporteEMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteEMDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLTMesDepartLayout = new javax.swing.GroupLayout(panelLTMesDepart);
        panelLTMesDepart.setLayout(panelLTMesDepartLayout);
        panelLTMesDepartLayout.setHorizontalGroup(
            panelLTMesDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLTMesDepartLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelLTMesDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLTMesDepartLayout.createSequentialGroup()
                        .addComponent(labelReporteEspecifico6)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(panelLTMesDepartLayout.createSequentialGroup()
                        .addGroup(panelLTMesDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLTMesDepartLayout.createSequentialGroup()
                                .addComponent(labelAnoEMD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputMesEMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelMesEMD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputAnoEMD, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonReporteEMD))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelLTMesDepartLayout.setVerticalGroup(
            panelLTMesDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLTMesDepartLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelReporteEspecifico6)
                .addGap(30, 30, 30)
                .addGroup(panelLTMesDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputAnoEMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMesEMD)
                    .addGroup(panelLTMesDepartLayout.createSequentialGroup()
                        .addGroup(panelLTMesDepartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAnoEMD)
                            .addComponent(inputMesEMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(botonReporteEMD)))
                .addGap(35, 35, 35))
        );

        setBackground(new java.awt.Color(245, 245, 245));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(750, 505));

        panelSuperior.setBackground(new java.awt.Color(245, 245, 245));
        panelSuperior.setBorder(null);
        panelSuperior.setPreferredSize(new java.awt.Dimension(759, 146));

        labelReporte.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelReporte.setForeground(new java.awt.Color(15, 15, 111));
        labelReporte.setText("REPORTES");

        labelListaReportes.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        labelListaReportes.setText("Lista de Reportes: ");

        comboReportes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Detalle de estudiantes en un curso por departamentos", "Detalle del reporte de notas por estudiante", "Cursos con mayor número de asistentes en el mes", "Historico de estudiantes que ha ganado un Curso", "Curso con menos potencial de avance", "Estudiantes que han llegado en el mes por departamento", "item6" }));
        comboReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelReporte)
                    .addComponent(labelListaReportes)
                    .addComponent(comboReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelReporte)
                .addGap(18, 18, 18)
                .addComponent(labelListaReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panelInferior.setBackground(new java.awt.Color(245, 245, 245));
        panelInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        panelInferior.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboReportesActionPerformed

    private void botonReporteCMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteCMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReporteCMAActionPerformed

    private void botonReporteEMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteEMDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReporteEMDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarMesAno;
    private javax.swing.JButton botonReporteCDE;
    private javax.swing.JButton botonReporteCMA;
    private javax.swing.JButton botonReporteEMD;
    private javax.swing.JButton botonReporteHEC;
    private javax.swing.JButton botonReporteNLT;
    private javax.swing.JComboBox comboReportes;
    private com.toedter.calendar.JYearChooser inputAno;
    private com.toedter.calendar.JYearChooser inputAnoEMD;
    private javax.swing.JTextField inputCedulaNLT;
    private javax.swing.JComboBox inputCodCohorteCMA;
    private javax.swing.JComboBox inputCodCurosHEC;
    private javax.swing.JComboBox inputCursoCodCDE;
    private com.toedter.calendar.JMonthChooser inputMes;
    private com.toedter.calendar.JMonthChooser inputMesEMD;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelAnoEMD;
    private javax.swing.JLabel labelCedulaNTL;
    private javax.swing.JLabel labelCodCohorteCMA;
    private javax.swing.JLabel labelCodCursoCED;
    private javax.swing.JLabel labelCodCursoHEC;
    private javax.swing.JLabel labelDepartementoCDE;
    private javax.swing.JLabel labelListaReportes;
    private javax.swing.JLabel labelMes;
    private javax.swing.JLabel labelMesEMD;
    private javax.swing.JLabel labelReportEspecifico;
    private javax.swing.JLabel labelReporte;
    private javax.swing.JLabel labelReporteEspecifico2;
    private javax.swing.JLabel labelReporteEspecifico3;
    private javax.swing.JLabel labelReporteEspecifico4;
    private javax.swing.JLabel labelReporteEspecifico5;
    private javax.swing.JLabel labelReporteEspecifico6;
    private javax.swing.JList listDepart;
    private javax.swing.JPanel panelBuscarMesAno;
    private javax.swing.JPanel panelCursoEstDepart;
    private javax.swing.JPanel panelCursoHistorico;
    private javax.swing.JPanel panelCursoMenosAvance;
    private javax.swing.JPanel panelEstdianteNotas;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelLTMesDepart;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JScrollPane scrollPanelListDepar;
    // End of variables declaration//GEN-END:variables
        
    // Controlador
    private ControladorReportes contReportes;
    
    
    private void actualizarPanelInferior(JPanel panelNuevo) {    
        panelInferior.removeAll();
        panelInferior.add(panelNuevo);
        panelInferior.repaint();
        panelInferior.updateUI();        
    } // Fin del metodo actualizarPanelInferior
    
    
    private void actualizarPanelBuscar(int index){
        switch (index) {
            case 0: {
                JPanel panelVacio = new JPanel();
                panelVacio.setBackground(new java.awt.Color(245, 245, 245));
                actualizarPanelInferior(panelVacio);
            };break;
                
            case 1: {
                actualizarPanelInferior(panelCursoEstDepart); 
                initInformationCurso();
            };break;           
                
            case 2: {
                actualizarPanelInferior(panelEstdianteNotas);
            };break;
            
            case 3: {
                actualizarPanelInferior(panelBuscarMesAno);
            };break;
                
            case 4: {                
                actualizarPanelInferior(panelCursoHistorico);
                initInformationCurso();
            };break;     
                
            case 5: {
                actualizarPanelInferior(panelCursoMenosAvance);
                initInformationCohorte();
            };break;
                
            case 6: {
                actualizarPanelInferior(panelLTMesDepart);
            };break;       
                
            case 7: {
           
            };break;
                
            case 8: {
                
            };break;
        };        
    } // Fin del metodo actualizarPanelBus    
       
    
    private void asignarEventos(EventosPanelLogin events){
        comboReportes.addActionListener(events);
        botonBuscarMesAno.addActionListener(events);
        botonReporteCDE.addActionListener(events);
        botonReporteNLT.addActionListener(events);    
        botonReporteHEC.addActionListener(events);
        botonReporteCMA.addActionListener(events);
        botonReporteEMD.addActionListener(events);
    } // Fin del metodo asignarEventos
    
    
    private void initInformationCurso(){
        contReportes = ControladorReportes.getInstance();
        ArrayList<String> listCursos = contReportes.listarCursos();
        inputCursoCodCDE.setModel(new javax.swing.DefaultComboBoxModel(new String[]{""}));
        inputCodCurosHEC.setModel(new javax.swing.DefaultComboBoxModel(new String[]{""}));        
        if (listCursos != null) {
            for (int i = 0; i < listCursos.size(); i++) {
                inputCursoCodCDE.addItem(listCursos.get(i));
                inputCodCurosHEC.addItem(listCursos.get(i));
            }
        }                   
    } // Fin del metodo initInformationCurso
    
    private void  initInformationCohorte(){
        contReportes = ControladorReportes.getInstance();
        ArrayList<String> listCohorte = contReportes.listarCohortes();
        inputCodCohorteCMA.setModel(new javax.swing.DefaultComboBoxModel(new String[]{""}));
        if (listCohorte != null) {
            for (int x = 0; x < listCohorte.size(); x++) {
                inputCodCohorteCMA.addItem(listCohorte.get(x));
            }
        }
    } // Fin del metodo initInformationCohorte
    
    
    private void mostrarMensaje(int tipo, String titulo, String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, titulo, tipo);
    } // Fin del metodo mostrarMensaje     
    
    private void mostrarReporte(JasperPrint informe, String titulo) {
        if (informe != null) {
            JasperViewer ventanaVisor = new JasperViewer(informe, false);
            ventanaVisor.setTitle(titulo);
            ventanaVisor.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo realizar el informe");
        }

    } // Fin del metodo  mostrarReporte   
    
    
    // Cursos con mayor asistencia en el mes (Top 10) - (GRAFICO)
    private void reporteCursosMayorAsistencia(){
        contReportes = ControladorReportes.getInstance();
        int ano = inputAno.getYear();
        int mes =  (inputMes.getMonth() + 1);         
        String result  = contReportes.reporteCursosMayorAsistencia(ano, mes);
        if (result.equals("OK")) {
            JasperPrint informe = contReportes.getInforme();
            mostrarReporte(informe, "Reporte");
        } else {
            mostrarMensaje(JOptionPane.ERROR_MESSAGE, "Error", result);          
        }           
    } // Fin del metodo reporteHistorioCurso      
    
    
    // Curso con menos potencial de avance (TOP 5) (GRAFICO)
    private void reporteCursoMenosAvance(){
        contReportes = ControladorReportes.getInstance();  
        String codCohorte = inputCodCohorteCMA.getSelectedItem().toString();
        System.out.println("--ssssssssssss-->" + codCohorte);
        // OJO CAMBIAR
        // JasperPrint informe = contReportes.reporteCursoMenosAvance(codCohorte);
        // mostrarReporte(informe, "Reporte");
    } //  Fin del metodo reporteCursoMenosAvance
    
    
    // Detalle de estudiantes en un curso por departamentos - (TABLA)	    
    private void reporteEstCursoDepar(){
        contReportes = ControladorReportes.getInstance();
        String idCurso = inputCursoCodCDE.getSelectedItem().toString();      
        String departamento = "";
        if (listDepart.getSelectedValue() != null) {
            departamento = ""+ listDepart.getSelectedValue();
        }
        String result = contReportes.reporteEstCurDepart(idCurso, departamento);
        if (result.equals("OK")) {
            JasperPrint informe = contReportes.getInforme();
            mostrarReporte(informe, "Reporte");
            inputCursoCodCDE.setSelectedIndex(0);
        } else {
            mostrarMensaje(JOptionPane.ERROR_MESSAGE, "Error", result);          
        }

    } // Fin del metodo reporteEstCursoDepar
    
    
    // Estudiantes que han llegado en el mes por departamento - (GRAFICO)
    private void reportEstMesDepar(){
        contReportes = ControladorReportes.getInstance();
        int ano = inputAnoEMD.getYear();
        int mes =  (inputMesEMD.getMonth() + 1);
        String  result = contReportes.reporteEstMesDepart(ano, mes);                
        if (result.equals("OK")) {
            JasperPrint informe = contReportes.getInforme();
            mostrarReporte(informe, "Reporte");
        } else {
            mostrarMensaje(JOptionPane.ERROR_MESSAGE, "Error", result);          
        }          
    }
        
    
    // Detalle del reporte de notas por	estudiante- (TABLA)
    private void reporteEstNotas() {
        contReportes = ControladorReportes.getInstance();
        String cedula = inputCedulaNLT.getText();
        String result = contReportes.reporteNotasEstudiante(cedula);                       
        if (result.equals("OK")) {
            JasperPrint informe = contReportes.getInforme();
            mostrarReporte(informe, "Reporte");
            inputCedulaNLT.setText("");
        } else {
            mostrarMensaje(JOptionPane.ERROR_MESSAGE, "Error", result);          
        }        
    } // Fin del metodo reporteEstNotas        
    

    // Historico de estudiantes que ha ganado un Curso - (TABLA)
    private void reporteHisEstGanadoCurso (){
        contReportes = ControladorReportes.getInstance();
        String codCurso = inputCodCurosHEC.getSelectedItem().toString();
        String result = contReportes.reporteHistoricoEstudCurso(codCurso);
        if (result.equals("OK")) {
            JasperPrint informe = contReportes.getInforme();
            mostrarReporte(informe, "Reporte");
            inputCodCurosHEC.setSelectedIndex(0);
        } else {
            mostrarMensaje(JOptionPane.ERROR_MESSAGE, "Error", result);          
        }                  
    } // Fin del metodo reporteHisEstGanadoCurso

    
    private class EventosPanelLogin implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == comboReportes) {
                int index = comboReportes.getSelectedIndex();
                actualizarPanelBuscar(index);
            }
            if (e.getSource() == botonBuscarMesAno) {
                reporteCursosMayorAsistencia();
            }
            
            if (e.getSource() == botonReporteCDE) {
                reporteEstCursoDepar();
            }
            
            if (e.getSource() == botonReporteNLT) {
                reporteEstNotas();
            }
            
            if (e.getSource() == botonReporteHEC) {
                reporteHisEstGanadoCurso();
            }
            
            if (e.getSource() == botonReporteCMA) {
                reporteCursoMenosAvance();
            }
            
            if (e.getSource() == botonReporteEMD) {
                reportEstMesDepar();
            }
            
        }
    
    } // Fin de la clase EventosPanelLogin

} // Fin de la clase PanelLogin
